project:
  name: kendra
  regions:
  - us-west-2
tests:
  default:
    template: ./templates/kendra.yaml
    regions:
    - us-west-2
    parameters:
      DatasourceS3bucketName: 'fsu-kendratest-noor'
      